cart/urls.py
from django.urls import path

from cart.views import cart_add, CartDetail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', CartDetail.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('article/', include('articleapp.urls', namespace='art')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('wallet/', include('purse.urls', namespace='wallet')),
    path('order/', include('orderapp.urls', namespace='order'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopapp/urls.py
from django.urls import path

from shopapp.views import ShowProduct, CategoryProduct, ProductDetail


app_name = 'shopapp'


urlpatterns = [
               path('catalog/', ShowProduct.as_view(), name='catalog'),
               path('catalog/<slug:slug_cat>/', CategoryProduct.as_view(), name='categories'),
               path('catalog/<slug:slug_cat>/<slug:slug>/', ProductDetail.as_view(), name='product')

]

shopapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:categories', kwargs={'slug_cat': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, related_name='products', default=_('not found'))
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product', kwargs={'slug_cat': self.category.slug, 'slug': self.slug})

shopapp/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from shopapp.models import Product, Category
from cart.forms import CartAddProductForm


class ShowProduct(ListView):
    model = Product
    template_name = 'shop/catalog.html'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ShowProduct, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class CategoryProduct(ListView):
    model = Product
    template_name = 'shop/catalog.html'
    context_object_name = 'product'
    allow_empty = False

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug_cat'], available=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryProduct, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'shop/product.html'
    slug_url_kwarg = 'slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        return context

    def get(self, request, *args, **kwargs):
        if get_object_or_404(Category, slug=kwargs['slug_cat']):
            return super(ProductDetail, self).get(request, *args, **kwargs)
        else:
            raise Http404

shopapp/templates/shop/catalog.html
{% extends 'base/index.html' %}

{% block content %}
{% load static %}
<!-- Header-->
<header class="bg-dark py-5 red-color">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder"> Каталог </h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop homepeage template</p>
        </div>
    </div>
</header>
<div class="container">
    <ul class="nav nav-pills nav-fill">
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'catalog' %}
                  active
                {% endif %}" aria-current="page" href="{% url 'shop:catalog' %}">Всё</a>
            </li>
            {% for category in categories %}
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.kwargs.slug_cat == category.slug %}
                  active
                {% endif %}" href="{% url 'shop:categories' category.slug%}" >{{category.name}}</a>
            </li>
            {% endfor %}
        </ul>

<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for item in product%}
            <div class="col mb-5 mob-card">
                <div class="card h-100">
                    <img class="card-img-top" src="/media/{{ item.image }}" alt="..."/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <a href="{{ item.get_absolute_url }}" style="text-decoration: none; color: black;">
                                <h4 class="fw-bolder">{{ item.name }}</h4>
                            </a>
                            <h5 class="fw-bolder">{{ item.short_desc }}</h5>
                            <!-- Product price-->
                            <p class="other_text">{{ item.price }} рублей</p>
                            <br>
                            <a class="main_anchor" href="{% url 'cart:cart_add' item.pk %}" style="font-size:14px; padding: 3px 5px; margin-top:5px"> В корзину </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>


{% endblock content %}
<!-- Footer-->

shopapp/templates/shop/product.html
{% extends 'base/index.html' %}

{% block content %}
{% load static %}
<!-- Header-->
<header class="bg-dark py-5 red-color">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder"> Каталог </h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop homepeage template</p>
        </div>
    </div>
</header>
<div class="container">

           <ul class="nav nav-pills nav-fill">
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'catalog' %}
                  active
                {% endif %}" aria-current="page" href="{% url 'shop:catalog' %}">Всё</a>
            </li>
            {% for category in categories %}
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.kwargs.slug_cat == category.slug %}
                  active
                {% endif %}" href="{% url 'shop:categories' category.slug%}" >{{category.name}}</a>
            </li>
            {% endfor %}
        </ul>

</div>
<div class="product container">
        <div class="product-name">
            <div class="product-img"> <img class="logo-product" src="/media//{{ product.image }}" alt="albom" width="400"
                    height="400">
            </div>
            <div class="product-name-title">
                    <h2 class="singer">{{ product.name }}</h2>
                <div class="specification">
                    <p>Осталось: {{ product.stock }} шт.</p>
                    <div class="describe_album">
                        <b>Описание</b>
                        <p>{{ product.description }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="product-price">
            <div class="how-match">
                <h3 class="price-name">Цена</h3>
                <h2 class="money">{{ product.price }} рублей</h2>
            </div>
            <div class="product-in-box">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input class="main_anchor card_anchor" type="submit" value="Добавить в корзину">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
<!-- Footer-->