articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleListView, ArticleGenresListView, ArticlePageView, add_like

app_name = 'articleapp'

urlpatterns = [
    path('', ArticleListView.as_view(), name='all'),
    path('<slug:slug_genres>', ArticleGenresListView.as_view(), name='genres'),
    path('page/<slug:slug>', ArticlePageView.as_view(), name='article'),
    path('likes/', add_like, name='likes')
]

authapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordResetDoneView,
    PasswordResetCompleteView
)

from .views import *


app_name = 'authapp'

urlpatterns = [
               path('login/', login, name='login'),
               path('logout/', logout, name='logout'),
               path('register/', register, name='register'),
               path('edit/user/', edit_user, name='edit'),
               path('edit/profile/', edit_profile, name='profile'),
               path('verify/<str:email>/<str:activation_key>', verify, name='verify'),
               path('password-change/', PassChangeView.as_view(), name='password_change'),
               path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
               path('password-reset/', PassResetView.as_view(), name='password_reset'),
               path('password-reset/done/', PasswordResetDoneView.as_view(),
                    name='password_reset_done'),
               url(r'password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PassResetConfirmView.as_view(),
                   name='password_reset_confirm'),
               path('password-reset/complete/', PasswordResetCompleteView.as_view(),
                    name='password_reset_complete')
               ]

cart/urls.py
from django.urls import path

from cart.views import cart_add, CartDetail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', CartDetail.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('article/', include('articleapp.urls', namespace='art')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('wallet/', include('purse.urls', namespace='wallet')),
    path('order/', include('orderapp.urls', namespace='order'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path

from .views import index, contact

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contact, name='contact')
]

shopapp/urls.py
from django.urls import path

from shopapp.views import ShowProduct, CategoryProduct, ProductDetail


app_name = 'shopapp'


urlpatterns = [
               path('catalog/', ShowProduct.as_view(), name='catalog'),
               path('catalog/<slug:slug_cat>/', CategoryProduct.as_view(), name='categories'),
               path('catalog/<slug:slug_cat>/<slug:slug>/', ProductDetail.as_view(), name='product')

]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render

from articleapp.models import ArticleModel


def index(request):
    new_post = ArticleModel.new_articles.first()
    top = ArticleModel.top.all()
    context = {'title': 'Ashtray Magazine',
               'top': top,
               'new_post': new_post
               }
    return render(request, 'base/index.html', context)


def contact(request):
    return render(request, 'base/contacts.html', {'title': 'Контакты'})

mainapp/templates/base/contacts.html
{% extends 'base/index.html' %}

{% block content %}
{% load static %}
       <header class="bg-dark py-5 red-color">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Контактные данные</h1>
                <p class="lead fw-normal text-white-50 mb-0">Свяжись с нами ...</p>
            </div>
        </div>
    </header>
    <div class="middle container">
        <div class="contact_data">
            <div class="contacts">
                <p class="avatar"><img src="{% static 'img/main/photo.png' %}" alt="women" width="299"></p>
                <h4 class="sub_sign"> Адрес </h4>
                <p class="text_contacts"> Ростов-на-Дону</p>
                <h4 class="sub_sign"> Телефоны </h4>
                <ol class="roman">
                    <li class="contact_list">+79773188482</li>
                    <li class="contact_list">+83945349234</li>
                </ol>
                <h4 class="sub_sign"> Онлайн сервисы </h4>
                <ul class="email">
                    <li class="contact_list">deadhunt96@yandex.ru</li>
                    <li class="contact_list">v.kolochikoff@yandex.ru</li>
                </ul>
            </div>
            <div class="order">
                <form action="#">
                    {% csrf_token %}
                    <h4 class="sub_sign"> Отправьте нам сообщение </h4>
                    <p class="order_text">ФИО</p>
                    <input class="entry for-mob" type="text" name="name" placeholder="Full Name">
                    <p class="order_text">Email</p>
                    <input class="entry for-mob" type="email" name="email" placeholder="mail@mail.ru">
                    <p class="order_text">Сообщение</p>
                    <textarea class="entry message for-mob" name="message"  cols="29" rows="9"></textarea><br>
                    <button class="but for-mob" type="submit">Отправить</button>
                </form>
            </div>
        </div>
        <div class="map">
            <h2 class="sub-header mb-5" style="text-align: center;"> Ищи нас здесь </h2>
            <iframe
                src="https://yandex.ru/map-widget/v1/?um=constructor%3Aa288981212cbb76bf89fc128159ff41761c2e8841ff4fa23b8896aa2a77a8763&amp;source=constructor"
                width="1140" height="600" frameborder="0"></iframe>
        </div>
    </div>
    </div>

 {% endblock content %}

mainapp/templates/base/index.html
{% load static %}

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="icon" type="image/png" href="{% static 'img/main/logo.svg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main/style.css' %}">
    <title>{% block title %} {{ title }} {% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid container">
            <a class="navbar-brand" href="/">
                <img class='logo' src="{% static 'img/main/logo.svg' %}" alt="" width="42" height="68"
                    class="d-inline-block align-text-top">
                Ashtray Magazine
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}">Контакты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'art:all' %}">Статьи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:catalog' %}">Магазин</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:edit' %}">
                        Пользователь: {{ user.first_name|default:'' }} | Баланс: {{ wallet }}
                        </a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
                    </li>
                    <li style="color: white;">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}" style="padding-top: 5px;">
                            <img src="{% static 'img/main/basket.png'%}" width="20">
                            {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                        <span class="basket_qty">
                                            {{ total_items }}
                                        </span>
                                {% endif %}
                            {% endwith %}
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:register' %}">Регистрация</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    <div class="top">
        <div class="header-page container">
            <div class="title-head">
                <h1 class="main">Ashtray Magazine - здесь любят говорить</h1>
                <p class="text">Мы независимое творческое объединение, состоящее из гиков и алкоголиков чуть более, чем
                    полностью. Здесь вы не найдёте нытья о злободневных проблемах (только если совсем чуть-чуть).</p>
                <a href="#144" class="main_anchor">Смотреть!</a>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <h2 class="sub-header" id="144">Категории товаров</h2>
            <div class="category">
                <div class="card">
                    <img class='object' src="{% static 'img/main/film.svg' %}" alt="vinyl">
                    <div class="describe">
                        <h3 class='category-name'>Кинематограф</h3>
                        <p class="describe-text">Широкий выбор винила с любимой музыкой! Быстрая доставка, гарантия!.
                            Диски и пластинки в наличии и под заказ!</p>
                        <a class='more' href="{% url 'art:genres' 'movie' %}">Перейти в раздел</a>
                    </div>

                </div>
                <div class="card card_1">
                    <img class='object' src="{% static 'img/main/game.svg' %}" alt="cd">
                    <div class="describe">
                        <h3 class='category-name'>Игровая индустрия</h3>
                        <p class="describe-text">Фирменные CD диски любимых групп и исполнителей покупайте с доставкой
                            на дом. Большой выбор фирменных музыкальных дисков</p>
                        <a class='more' href="{% url 'art:genres' 'game' %}"> Перейти в раздел </a>
                    </div>
                </div>
                <div class="card card_2">
                    <img class='object' src="{% static 'img/main/music.svg' %}" alt="player">
                    <div class="describe">
                        <h3 class='category-name'>Музыка</h3>
                        <p class="describe-text">Виниловые проигрыватели от мировых брендов. Официальные поставки.
                            Гарантия качества! Выгодные цены на товары каталога.</p>
                        <a class='more' href="{% url 'art:genres' 'music' %}">Перейти в раздел</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="container">
            <h2 class="sub-header">Актуальное</h2>
            <p class="other_text">Последняя статья на сайте</p>
            <a href="{{new_post.get_absolute_url}}">
                <div class="picture">
                <img class="picture_img" src="{{ new_post.img_main.url}}" alt="picture" width="100%">
                <p class="picture_text_first"> {{new_post.title}}</p>
            </div>
            </a>
        </div>
        <div class="container">
            <h2 class="sub-header">Популярное</h2>
            <p class="other_text">Самое горячо обсуждаемое</p>
            <div class="category">
                {% for post in top %}
                <a href="{{post.get_absolute_url}}">
                    <div class="card article">
                    <img class='poster' src="{{post.img_mini.url}}" alt="poster2">
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock content %}
    <br>
    <div class="footer">
        <div class="container footer_box">
            <div class="footer_top">
                <div class="question">
                    <h3 class="question_sign"> Хотите кривой сайт? <br>Звоните! Пишите!</h3>
                    <ol class="bot_order">
                        <li class="data"><a class='data'
                                href="mailto:v.kolokolchikoff@yandex.ru">v.kolokolchikoff@yandex.ru</a>
                        </li>
                        <li class="data"><a class='data' href="tel:+732462831232">+7(324)628-312-32</a></li>
                    </ol>
                </div>
                <div class="call">
                    <a href="#" class="main_anchor">Let`s Talk</a>
                </div>
            </div>

            <div class="copy">
                <p>Все права защищены &copy;</p>
            </div>
        </div>
    </div>
</body>

</html>