articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleListView, ArticleGenresListView, ArticlePageView, add_like

app_name = 'articleapp'

urlpatterns = [
    path('', ArticleListView.as_view(), name='all'),
    path('<slug:slug_genres>', ArticleGenresListView.as_view(), name='genres'),
    path('page/<slug:slug>', ArticlePageView.as_view(), name='article'),
    path('likes/', add_like, name='likes')
]

cart/urls.py
from django.urls import path

from cart.views import cart_add, CartDetail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', CartDetail.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('article/', include('articleapp.urls', namespace='art')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('wallet/', include('purse.urls', namespace='wallet')),
    path('order/', include('orderapp.urls', namespace='order'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articleapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import ugettext as _

from core.settings import AUTH_USER_MODEL


def choose_path(instance, filename: str):
    return f'root_file/articles/{instance.slug}/{filename}'


class Author(models.Model):
    user_id = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('authors'))

    def __str__(self):
        return f'{self.user_id.last_name}'

    @property
    def full_name(self):
        return f'{self.user_id.first_name} {self.user_id.last_name} '


class Genres(models.Model):
    class Meta:
        ordering = ('name',)
    name = models.CharField(verbose_name=_('genre'), max_length=16)
    slug = models.SlugField(verbose_name=_('slug'))

    def __str__(self):
        return f'{self.name} - {self.pk}'

    def get_absolute_url(self):
        return reverse('art:genres', kwargs={'slug_genre': self.slug})


class ContentQuerySet(models.QuerySet):
    def new_content(self):
        return self.order_by('publish')[0]


class TopContent(models.QuerySet):
    def get_top(self):
        return self.raw("""
                select * from articleapp_articlemodel aa  where aa.id in (select a.id from articleapp_articlemodel a
                left join articleapp_modellikesarticle am
                on am.article_id_id = a.id
                left join authapp_user ac
                on ac.id = am.user_id_id
                group by a.id order by count(am.id) desc  limit 3)""")


class ArticleModel(models.Model):
    class Meta:
        ordering = ('-publish',)

    title = models.CharField(max_length=70, verbose_name=_('title'), default=_('Not found'))
    short_describe = models.TextField(verbose_name=_('short describe'), max_length=150, default=_('Not Found'))
    owner_id = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True,
                                 verbose_name=_('owner'), related_name='owner')
    genres_id = models.ManyToManyField(Genres, related_name='genres', related_query_name='genre')
    slug = models.SlugField(max_length=70, unique_for_date='publish')
    text = models.TextField(verbose_name=_('text'), null=True)
    img_mini = models.ImageField(upload_to=choose_path, verbose_name=_('image mini'))
    img_main = models.ImageField(upload_to=choose_path, verbose_name=_('image main'))

    is_active = models.BooleanField(verbose_name='active', default=True)
    publish = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    new_articles = ContentQuerySet.as_manager()
    top = TopContent().as_manager()

    def __str__(self):
        return f'{self.title} - {self.pk}'

    def get_absolute_url(self):
        return reverse('art:article', kwargs={'slug': self.slug})


class ArticleUserModel(models.Model):
    class Meta:
        abstract = True

    user_id = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                                verbose_name=_('user'))
    article_id = models.ForeignKey('ArticleModel', on_delete=models.CASCADE,
                                   verbose_name=_('article'))
    status = models.BooleanField(verbose_name='status', max_length=5, default=True)

    def __str__(self):
        return f'{self.user_id.first_name} {self.user_id.last_name} - comment {self.id}'


class ModelLikesArticle(ArticleUserModel):
    class Meta:
        unique_together = (("user_id", "article_id"),)


class CommentsModel(ArticleUserModel):
    class Meta:
        ordering = ('created_at',)

    text = models.TextField(verbose_name=_('comment'), max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user_id.first_name} - date: {self.created_at}'


class ModelLikesComment(ArticleUserModel):
    class Meta:
        unique_together = (("user_id", "comment_id"),)

    comment_id = models.ForeignKey(CommentsModel, on_delete=models.CASCADE)

articleapp/forms.py
from django import forms

from articleapp.models import CommentsModel


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentsModel
        fields = ('user_id', 'article_id', 'text')

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name in ('user_id', 'article_id'):
                field.widget = forms.HiddenInput()
            field.widget.attrs['class'] = 'form-control'

articleapp/views.py
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.views.generic.base import RedirectView
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from articleapp.models import ArticleModel, Genres, CommentsModel, ModelLikesArticle
from articleapp.forms import CommentForm


class ArticleListView(ListView):
    queryset = ArticleModel.objects.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'article/article_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['genres'] = Genres.objects.all()
        return context


class ArticleGenresListView(ListView):
    model = ArticleModel
    template_name = 'article/article_list.html'
    paginate_by = 5
    context_object_name = 'posts'

    def get_queryset(self):
        return ArticleModel.objects.filter(genres_id__slug=self.kwargs['slug_genres'], is_active=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleGenresListView, self).get_context_data(**kwargs)
        context['genres'] = Genres.objects.all()
        return context
    
    def get(self, request, *args, **kwargs):
        if get_object_or_404(Genres, slug=kwargs['slug_genres']):
            return super(ArticleGenresListView, self).get(request, *args, **kwargs)


class ArticlePageView(DetailView, RedirectView):
    model = ArticleModel
    template_name = 'article/detail.html'
    slug_url_kwarg = 'slug'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticlePageView, self).get_context_data(**kwargs)
        context['comments'] = CommentsModel.objects.filter(article_id=context['post'], status=True)
        article_info = {'user_id': self.request.user, 'article_id': context['post']}
        context['total_cost'] = context['post'].modellikesarticle_set.filter(status=True).count()
        if not self.request.user.is_anonymous:
            context['active_like'] = ModelLikesArticle.objects.filter(
                user_id=self.request.user,
                article_id=context['post'],
            ).first()
            context['comment_form'] = CommentForm(initial=article_info)
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
@require_POST
def add_like(request):
    post = ArticleModel.objects.get(pk=request.POST.get('article_id'))
    like, status = ModelLikesArticle.objects.get_or_create(user_id=request.user, article_id=post)
    like.status = False if not status and like.status else True
    like.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

articleapp/templates/article/article_list.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}
    <header class="bg-dark py-5 red-color">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">AshtrayMagazine</h1>
                <p class="lead fw-normal text-white-50 mb-0">Чтиво на любой вкус</p>
            </div>
        </div>
    </header>
<div class="container">
     <ul class="nav nav-pills nav-fill mb-20">
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'all' %}
                  active
                {% endif %}" aria-current="page" href="{% url 'art:all' %}">Всё</a>
            </li>
            {% for genre in genres %}
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.kwargs.slug_genres == genre.slug %}
                  active
                {% endif %}" href="{% url 'art:genres' genre.slug %}" >{{genre.name}}</a>
            </li>
            {% endfor %}
        </ul>
    <div class="order">
            <ul class="list-articles">
                {% for p in posts %}
                        <li> <div class="article-panel">
                <p class="first">Категория: {% for genre in p.genres_id.all %}
                    <a class="genres" href="{% url 'art:genres' genre.slug %}"> {{genre.name }}</a>
                    {% if not forloop.last %}| {% endif %}
                    {% endfor %}
                </p>
                <p class="last">Дата: {{p.publish|date:"d-m-Y H:i:s"}}</p>
            </div>

            {% if p.img_mini %}
                <p><img class="img-article-left thumb" src="{{p.img_mini.url}}"></p>
            {% endif %}
                            <h2><a class="parent" href="{{p.get_absolute_url}}">{{p.title}}</a></h2>
                {% autoescape on %}
                {{p.text|safe|linebreaks|truncatewords:50}}
                {% endautoescape %}
                        <div class="clear"></div>
                        <p class="link-read-post"><a href="{s{ p.get_abolute_url }}" >Читать статью</a></p>
                        </li>
                {% endfor %}
            </ul>
         {% include "article/pagination.html" with page=page_obj %}
    </div>
</div>
<br>
{% endblock %}

articleapp/templates/article/detail.html
{% extends 'base/index.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="order article-page">
        <div class="article-panel">
                <p class="first"><a class="back" href="{% url 'art:all' %}">Назад</a>
                </p>
                <p class="last">Дата: {{post.publish|date:"d-m-Y H:i:s"}}</p>
            </div>
        <div>
            <h1 class="display-4 fw-bolder mb-20"> {{post.title}} </h1>
            <img class="article-main-img mb-20" src="{{ post.img_main.url }}">
            <br>
            {{ post.text | safe | linebreaks }}
            <br>
            <div class="panel-bottom">
                <div class="like-block">
                    <form action="{% url 'art:likes' %}#like" method="POST">
                        {% csrf_token %}
                        <button  class="like {% if active_like.status %} active-like {% endif %}"
                                type="submit" name="article_id" value="{{post.pk}}" >
                            <img src="{% static 'img/main/like.png' %}" width="20">
                        </button>
                    </form>
                    <p id="like">{{total_cost}}</p>
                </div>
                <p class="last">Автор: {{post.owner_id.full_name}}</p>
        </div>
        {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
        <ul class="list-articles list-comments">
        {% for comment in comments %}
            <li class="comment mb-20"> <div class="article-panel">
                <p class="first"><img src="{{comment.user_id.userprofile.avatar.url}}" width="40">
                {{comment.user_id.userprofile.full_name}}
                </p>
                <p class="last">Дата: {{comment.created_at|date:"d-m-Y H:i:s"}}</p>
            </div>
                <div class="text-comment">
                    <p>{{comment.text}}</p>
                </div>

            </li>
            {% empty %}
                <p>There are no comments yet.</p>
            {% endfor %}
            </ul>
                {% if user.is_authenticated%}
                    <h2>Add a new comment</h2>
                    <form action="{% url 'art:article' post.slug %}" method="post">
                        {{ comment_form.as_p }}
                        {% csrf_token %}
                        <p><input type="submit" value="Add comment"></p>
                    </form>
                {% endif %}
    </div>
</div>
</div>
{% endblock content %}

articleapp/templates/article/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">&lt;</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">&gt;</a>
        {% endif %}
    </span>
</div>